baseURL = "https://www.cansurmeli.com/"
languageCode = "en-us"
title = "CAN"
theme = "minimal"

pygmentsStyle = "native"
pygmentsOptions = "linenos=table"

[params]
	author = "Can Sürmeli"
	description = "an eager to learn developer who hacks things and cares deeply about UI/UX; and also a sportsman"
	githubUsername = "cansurmeli"
	highlight = true
	highlightStyle = "solarized-dark"
	highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
	copyright= "Powered by [Hugo](https://gohugo.io)"

[params.matomo]
	url = "https://analytics.cansurmeli.com/"

[params.staticman]
	endpoint = "https://api.staticman.net/v2/entry/"
	username = "cansurmeli"
	repository = "cansurmeli.com"
	branch = "master"

[[menu.main]]
	url = "/"
	name = "Home"
	weight = 1

[[menu.main]]
	url = "/about-me/"
	name = "About Me"
	weight = 2

[[menu.main]]
	url = "/excerpts/"
	name = "Excerpts"
	weight = 3

[[menu.main]]
	url = "/posts/"
	name = "Posts"
	weight = 4

[[menu.main]]
	url = "/lncs/"
	name = "LNCS"
	weight = 5

[[menu.main]]
	url = "/reviews/"
	name = "Reviews"
	weight = 6

[[menu.icon]]
	url = "mailto:c_surmeli@icloud.com"
	name = "far fa-envelope"
	weight = 1

[[menu.icon]]
	url = "https://github.com/cansurmeli/"
	name = "fab fa-github"
	weight = 2

[[menu.icon]]
	url = "https://twitter.com/cansurmeli/"
	name = "fab fa-twitter"
	weight = 3

[[menu.icon]]
	url = "https://stackoverflow.com/users/1169053/can-sürmeli"
	name = "fab fa-stack-overflow"
	weight = 4

[[menu.icon]]
	url = "https://www.500px.com/c_surmeli"
	name = "fab fa-500px"
	weight = 5

